SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `favoritemovies`;
DROP TABLE IF EXISTS `logindatas`;
DROP TABLE IF EXISTS `movies`;
DROP TABLE IF EXISTS `users`;
SET FOREIGN_KEY_CHECKS = 1;